repos:
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0   # pin a release
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        additional_dependencies: [yamllint==1.35.1]